# Generated by Django 5.0.6 on 2024-05-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBN', models.CharField(max_length=200)),
                ('School_Name', models.CharField(default=0, max_length=200)),
                ('Number_of_Test_Takers', models.IntegerField(default=0)),
                ('Critical_Reading_Mean', models.IntegerField(default=0)),
                ('Mathematics_Mean', models.IntegerField(default=0)),
                ('Writing_Mean', models.IntegerField(default=0)),
            ],
        ),
    ]
